name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: custom-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install flake8 and pytest
      run: pip install -r sample_app/requirements.txt

    - name: Lint
      run: |
          pip install flake8
          flake8 sample_app/

    - name: Test
      run: |
           pip install pytest
           pytest test.py # or custom test command

    - name: Build Docker image
      run: sudo docker build -t radicald/flaskapp:${{ github.sha }} sample_app/

    - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Push image to Dockerhub
      run: sudo docker push radicald/flaskapp:${{ github.sha }}

    - name: Deploy
      run: docker run -d --name flaskapp radicald/flaskapp:${{ github.sha }} 
