name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: custom-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install flake8 and pytest
      run: pip install -r requirements.txt

    - name: Lint
      run: flake8 ./sample-app/main.py

    - name: Test
      run: pytest ./sample-app/main.py # or custom test command

    - name: Build Docker image
      run: docker build -t radicald/flaskapp:${{ github.sha }} ./sample-app

    - name: Push image to Dockerhub
      run: docker push radicald/flaskapp:${{ github.sha }}

    - name: Deploy
      run: docker run -d --name flaskapp radicald/flaskapp:${{ github.sha }} 
